apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: routernetes
  namespace: openshift-operators
spec:
  channel: alpha
  name: routernetes-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
