apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routernetes
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: apps/routernetes
    repoURL: 'https://github.com/vrutkovs/routershift'
    targetRevision: routernetes
  syncPolicy:
    automated: {}
